//! Note pages: list, show, and the form for new and edit, built from `ui.*`.
//! Generated by the loco-ui scaffold templates; edit freely.

use loco_rs::controller::views::pagination::PagerMeta;
use loco_ui::{prelude::*, table::Row};

use crate::models::_entities::notes::Model;

/// The model as the form's `(name, value)` pairs, for the edit page.
pub fn values(m: &Model) -> Vec<(String, String)> {
    vec![
        ("title".into(), m.title.to_string()),
        (
            "body".into(),
            m.body.as_ref().map(ToString::to_string).unwrap_or_default(),
        ),
        ("done".into(), m.done.to_string()),
        (
            "due".into(),
            m.due.as_ref().map(ToString::to_string).unwrap_or_default(),
        ),
    ]
}

/// Every note on this page, with the pager from Loco's paging answer.
pub fn list(ui: &Ui, rows: &[Model], meta: &PagerMeta) -> Markup {
    let table = ui
        .table("notes", "/notes")
        .column("id", "Id")
        .column("title", "Title")
        .column("body", "Body")
        .column("done", "Done")
        .column("due", "Due");
    let rows = rows.iter().map(|m| {
        let v = values(m);
        let href = format!("/notes/{}", m.id);
        let mut cells = vec![html! { a href=(href) { (m.id) } }];
        cells.extend(v.iter().map(|(_, value)| html! { (value) }));
        Row::new(cells)
    });
    html! {
        (ui.flash())
        h1 { "Notes" }
        (table.rows(rows).paged_from(meta))
        (ui.link_button("New note", "/notes/new"))
    }
}

/// One note: its fields, an edit link and a delete button.
pub fn show(ui: &Ui, m: &Model) -> Markup {
    let labels = ["Title", "Body", "Done", "Due"];
    let action = format!("/notes/{}/delete", m.id);
    let edit = format!("/notes/{}/edit", m.id);
    html! {
        (ui.flash())
        h1 { "Note " (m.id) }
        dl {
            @for (label, (_, value)) in labels.iter().zip(values(m)) {
                dt { (label) }
                dd { (value) }
            }
        }
        form method="post" action=(action) {
            (ui.link_button("Edit", &edit))
            " "
            (ui.button("Delete").danger().submit())
        }
    }
}

/// The form for new (`action` = the list) and edit (`action` = the item), with what was
/// posted and the messages when it comes back.
pub fn form(
    ui: &Ui,
    title: &str,
    action: &str,
    values: &[(String, String)],
    errors: &[(&str, &str)],
) -> Markup {
    let form = ui
        .form(action)
        .text("title", "Title")
        .required()
        .textarea("body", "Body", 4)
        .checkbox("done", "Done")
        .date("due", "Due", "1900-01-01", "2100-12-31")
        .values(values)
        .errors(errors)
        .submit("Save");
    html! {
        h1 { (title) }
        (form)
    }
}
