to: src/controllers/{{ snake_plural }}.rs
skip_exists: true
message: "Controller `{{ pascal_singular }}` (HTML, loco-ui) was added successfully.{% if auth %} Its routes require a JWT — re-run with `--no-auth` to generate public routes.{% endif %}"
injections:
- into: src/controllers/mod.rs
  append: true
  content: "pub mod {{ snake_plural }};"
- into: src/app.rs
  after: "AppRoutes::"
  content: "            .add_route(controllers::{{ snake_plural }}::routes())"
---
//! {{ pascal_singular }} pages: list, show, new, edit and delete as plain HTML forms with
//! Post/Redirect/Get. Generated by the loco-ui scaffold templates; edit freely.
#![allow(clippy::unused_async)]
use loco_ui::{loco::Valid, prelude::*};
use loco_rs::prelude::*;
use serde::Deserialize;
{%- if prelude_use %}
#[allow(unused_imports)] // Loco lists the timestamp types too
{{ prelude_use }}
{%- endif %}

use crate::{
    models::_entities::{{ snake_plural }}::{ActiveModel, Column, Entity, Model},
    views,
};

/// The posted fields. `Valid<Params>` reads them, or gives back a message for every field in
/// error and what was posted; add `#[validate(..)]` rules here.
#[derive(Deserialize, Validate)]
struct Params {
{%- for f in fields %}
{%- if f.input_kind == "checkbox" and not f.nullable %}
    #[serde(default, deserialize_with = "loco_ui::loco::checkbox")]
    {{ f.field_name }}: bool,
{%- elif f.is_enum %}
    {{ f.field_name }}: {% if f.nullable %}Option<String>{% else %}String{% endif %},
{%- else %}
    {{ f.field_name }}: {{ f.rust_type }},
{%- endif %}
{%- endfor %}
}

fn set(item: &mut ActiveModel, p: Params) {
{%- for f in fields %}
    item.{{ f.field_name }} = Set(p.{{ f.field_name }});
{%- endfor %}
}

async fn load(ctx: &AppContext, id: i64) -> Result<Model> {
    Entity::find_by_id(id).one(&ctx.db).await?.ok_or(Error::NotFound)
}

#[debug_handler]
async fn list(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
) -> Result<Page> {
    let table = ui.table("{{ snake_plural }}", "");
    let wanted = query::PaginationQuery {
        page: table.page() as u64,
        page_size: table.per_page() as u64,
    };
    let found = query::fetch_page(&ctx.db, Entity::find().order_by_asc(Column::Id), &wanted).await?;
    Ok(ui.page("{{ pascal_plural }}", views::{{ snake_plural }}::list(&ui, &found.page, &found.meta)))
}

#[debug_handler]
async fn show(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let item = load(&ctx, id).await?;
    Ok(ui.page("{{ pascal_singular }}", views::{{ snake_plural }}::show(&ui, &item)))
}

// No `State` here, so name it for the `auth::JWT` check.
#[debug_handler(state = AppContext)]
async fn new(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
) -> Result<Page> {
    let title = "New {{ snake_singular | replace(from="_", to=" ") }}";
    let form = views::{{ snake_plural }}::form(&ui, title, "/{{ snake_plural }}", &[], &[]);
    Ok(ui.page(title, form))
}

#[debug_handler]
async fn create(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let p = match form {
        Ok(p) => p,
        Err(bad) => {
            let title = "New {{ snake_singular | replace(from="_", to=" ") }}";
            let body = views::{{ snake_plural }}::form(&ui, title, "/{{ snake_plural }}", &bad.values, &bad.errors.pairs());
            return Ok(ui.page(title, body).into_response());
        }
    };
    let mut item = ActiveModel {
        ..Default::default()
    };
    set(&mut item, p);
    let item = item.insert(&ctx.db).await?;
    let to = format!("/{{ snake_plural }}/{}", item.id);
    Ok(ui.redirect(&to).ok("Created.").into_response())
}

#[debug_handler]
async fn edit(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let item = load(&ctx, id).await?;
    let action = format!("/{{ snake_plural }}/{id}");
    let title = "Edit {{ snake_singular | replace(from="_", to=" ") }}";
    let form = views::{{ snake_plural }}::form(&ui, title, &action, &views::{{ snake_plural }}::values(&item), &[]);
    Ok(ui.page(title, form))
}

#[debug_handler]
async fn update(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let item = load(&ctx, id).await?;
    let action = format!("/{{ snake_plural }}/{id}");
    let p = match form {
        Ok(p) => p,
        Err(bad) => {
            let title = "Edit {{ snake_singular | replace(from="_", to=" ") }}";
            let body = views::{{ snake_plural }}::form(&ui, title, &action, &bad.values, &bad.errors.pairs());
            return Ok(ui.page(title, body).into_response());
        }
    };
    let mut item = item.into_active_model();
    set(&mut item, p);
    item.update(&ctx.db).await?;
    Ok(ui.redirect(&action).ok("Saved.").into_response())
}

#[debug_handler]
async fn remove(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Redirect> {
    load(&ctx, id).await?.into_active_model().delete(&ctx.db).await?;
    Ok(ui.redirect("/{{ snake_plural }}").ok("Deleted."))
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("/{{ snake_plural }}")
        .add("/", get(list).post(create))
        .add("/new", get(new))
        .add("/{id}", get(show).post(update))
        .add("/{id}/edit", get(edit))
        .add("/{id}/delete", post(remove))
}
