to: src/views/{{ snake_plural }}.rs
skip_exists: true
message: "Views `views::{{ snake_plural }}` (Maud, loco-ui) were added successfully."
injections:
- into: src/views/mod.rs
  append: true
  content: "pub mod {{ snake_plural }};"
---
//! {{ pascal_singular }} pages: list, show, and the form for new and edit, built from `ui.*`.
//! Generated by the loco-ui scaffold templates; edit freely.

use loco_ui::{prelude::*, table::Row};

use crate::models::_entities::{{ snake_plural }}::Model;

/// The model as the form's `(name, value)` pairs, for the edit page.
pub fn values(m: &Model) -> Vec<(String, String)> {
    vec![
{%- for f in fields %}
{%- if f.input_kind == "datetime" %}
{%- if f.nullable %}
        ("{{ f.field_name }}".into(), m.{{ f.field_name }}.map(|v| format!("{v:?}")).unwrap_or_default()),
{%- else %}
        ("{{ f.field_name }}".into(), format!("{:?}", m.{{ f.field_name }})),
{%- endif %}
{%- elif f.nullable %}
        ("{{ f.field_name }}".into(), m.{{ f.field_name }}.as_ref().map(ToString::to_string).unwrap_or_default()),
{%- else %}
        ("{{ f.field_name }}".into(), m.{{ f.field_name }}.to_string()),
{%- endif %}
{%- endfor %}
    ]
}

/// Every {{ snake_singular }} on this page, with the pager for `total`.
pub fn list(ui: &Ui, rows: &[Model], total: usize) -> Markup {
    let table = ui
        .table("{{ snake_plural }}", "/{{ snake_plural }}")
        .column("id", "Id")
{%- for f in fields %}
        .column("{{ f.field_name }}", "{{ f.label }}")
{%- endfor %};
    let rows = rows.iter().map(|m| {
        let v = values(m);
        let href = format!("/{{ snake_plural }}/{}", m.id);
        let mut cells = vec![html! { a href=(href) { (m.id) } }];
        cells.extend(v.iter().map(|(_, value)| html! { (value) }));
        Row::new(cells)
    });
    html! {
        (ui.flash())
        h1 { "{{ pascal_plural }}" }
        (table.rows(rows).paged(total))
        (ui.link_button("New {{ snake_singular | replace(from="_", to=" ") }}", "/{{ snake_plural }}/new"))
    }
}

/// One {{ snake_singular }}: its fields, an edit link and a delete button.
pub fn show(ui: &Ui, m: &Model) -> Markup {
    let labels = [{% for f in fields %}"{{ f.label }}", {% endfor %}];
    let action = format!("/{{ snake_plural }}/{}/delete", m.id);
    let edit = format!("/{{ snake_plural }}/{}/edit", m.id);
    html! {
        (ui.flash())
        h1 { "{{ pascal_singular }} " (m.id) }
        dl {
            @for (label, (_, value)) in labels.iter().zip(values(m)) {
                dt { (label) }
                dd { (value) }
            }
        }
        form method="post" action=(action) {
            (ui.link_button("Edit", &edit))
            " "
            (ui.button("Delete").danger().submit())
        }
    }
}

/// The form for new (`action` = the list) and edit (`action` = the item), with what was
/// posted and the messages when it comes back.
pub fn form(
    ui: &Ui,
    title: &str,
    action: &str,
    values: &[(String, String)],
    errors: &[(&str, &str)],
) -> Markup {
    let form = ui
        .form(action)
{%- for f in fields %}
{%- if f.is_enum %}
        .select("{{ f.field_name }}", "{{ f.label }}", [{% for e in enums %}{% if e.enum_type == f.enum_type %}{% for v in e.variants %}"{{ v.value }}", {% endfor %}{% endif %}{% endfor %}])
{%- elif f.input_kind == "checkbox" %}
        .checkbox("{{ f.field_name }}", "{{ f.label }}")
{%- elif f.input_kind == "textarea" %}
        .textarea("{{ f.field_name }}", "{{ f.label }}", 4)
{%- elif f.input_kind == "date" %}
        .date("{{ f.field_name }}", "{{ f.label }}", "1900-01-01", "2100-12-31")
{%- elif f.input_kind == "datetime" %}
        .text("{{ f.field_name }}", "{{ f.label }}")
        .placeholder("2026-01-31T09:00:00")
{%- else %}
        .text("{{ f.field_name }}", "{{ f.label }}")
{%- endif %}
{%- if not f.nullable and f.input_kind != "checkbox" %}
        .required()
{%- endif %}
{%- endfor %}
        .values(values)
        .errors(errors)
        .submit("Save");
    html! {
        h1 { (title) }
        (form)
    }
}
