to: src/controllers/{{ snake_plural }}.rs
skip_exists: true
message: "Controller `{{ pascal_singular }}` (HTML, axum-nojs) was added successfully.{% if auth %} Its routes require a JWT — re-run with `--no-auth` to generate public routes.{% endif %}"
injections:
- into: src/controllers/mod.rs
  append: true
  content: "pub mod {{ snake_plural }};"
- into: src/app.rs
  after: "AppRoutes::"
  content: "            .add_route(controllers::{{ snake_plural }}::routes())"
---
//! {{ pascal_singular }} pages: list, show, new, edit and delete as plain HTML forms with
//! Post/Redirect/Get. Generated by the axum-nojs scaffold templates; edit freely.
#![allow(clippy::unused_async)]
use axum_nojs::{loco::Submitted, prelude::*};
use loco_rs::prelude::*;
{%- if prelude_use %}
{{ prelude_use }}
{%- endif %}

use crate::{
    models::_entities::{{ snake_plural }}::{ActiveModel, Column, Entity, Model},
    views,
};

/// The posted fields, parsed; `None` (with messages in `form`) when any is missing or wrong.
struct Params {
{%- for f in fields %}
{%- if f.is_enum %}
    {{ f.field_name }}: {% if f.nullable %}Option<String>{% else %}String{% endif %},
{%- else %}
    {{ f.field_name }}: {{ f.rust_type }},
{%- endif %}
{%- endfor %}
}

fn params(form: &mut Submitted) -> Option<Params> {
{%- for f in fields %}
{%- if f.input_kind == "checkbox" and not f.nullable %}
    let {{ f.field_name }} = form.checkbox("{{ f.field_name }}");
{%- elif f.is_enum %}
    let {{ f.field_name }} = form.{% if f.nullable %}optional{% else %}required{% endif %}::<String>("{{ f.field_name }}");
{%- elif f.nullable %}
    let {{ f.field_name }} = form.optional::<{{ f.rust_type | replace(from="Option<", to="") | trim_end_matches(pat=">") }}>("{{ f.field_name }}");
{%- else %}
    let {{ f.field_name }} = form.required::<{{ f.rust_type }}>("{{ f.field_name }}");
{%- endif %}
{%- endfor %}
    if !form.is_ok() {
        return None;
    }
    Some(Params {
{%- for f in fields %}
{%- if (f.input_kind == "checkbox" and not f.nullable) or f.nullable %}
        {{ f.field_name }},
{%- else %}
        {{ f.field_name }}: {{ f.field_name }}?,
{%- endif %}
{%- endfor %}
    })
}

fn set(item: &mut ActiveModel, p: Params) {
{%- for f in fields %}
    item.{{ f.field_name }} = Set(p.{{ f.field_name }});
{%- endfor %}
}

async fn load(ctx: &AppContext, id: i64) -> Result<Model> {
    Entity::find_by_id(id).one(&ctx.db).await?.ok_or(Error::NotFound)
}

#[debug_handler]
async fn list(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
) -> Result<Page> {
    let pages = Entity::find()
        .order_by_asc(Column::Id)
        .paginate(&ctx.db, ui.table("{{ snake_plural }}", "").per_page() as u64);
    let total = pages.num_items().await? as usize;
    let page = ui.table("{{ snake_plural }}", "").page() as u64;
    let rows = pages.fetch_page(page.saturating_sub(1)).await?;
    Ok(ui.page("{{ pascal_plural }}", views::{{ snake_plural }}::list(&ui, &rows, total)))
}

#[debug_handler]
async fn show(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let item = load(&ctx, id).await?;
    Ok(ui.page("{{ pascal_singular }}", views::{{ snake_plural }}::show(&ui, &item)))
}

#[debug_handler]
async fn new(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
) -> Result<Page> {
    let form = views::{{ snake_plural }}::form(&ui, "/{{ snake_plural }}", &[], &[]);
    Ok(ui.page("New {{ snake_singular | replace(from="_", to=" ") }}", form))
}

#[debug_handler]
async fn create(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Form(posted): Form<Vec<(String, String)>>,
) -> Result<Response> {
    let mut form = Submitted::new(posted);
    let Some(p) = params(&mut form) else {
        let errors = form.errors();
        let body = views::{{ snake_plural }}::form(&ui, "/{{ snake_plural }}", form.values(), &errors.pairs());
        return Ok(ui.page("New {{ snake_singular | replace(from="_", to=" ") }}", body).into_response());
    };
    let mut item = ActiveModel::default();
    set(&mut item, p);
    let item = item.insert(&ctx.db).await?;
    let to = format!("/{{ snake_plural }}/{}", item.id);
    Ok(ui.redirect(&to).ok("Created.").into_response())
}

#[debug_handler]
async fn edit(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let item = load(&ctx, id).await?;
    let action = format!("/{{ snake_plural }}/{id}");
    let form = views::{{ snake_plural }}::form(&ui, &action, &views::{{ snake_plural }}::values(&item), &[]);
    Ok(ui.page("Edit {{ snake_singular | replace(from="_", to=" ") }}", form))
}

#[debug_handler]
async fn update(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
    Form(posted): Form<Vec<(String, String)>>,
) -> Result<Response> {
    let item = load(&ctx, id).await?;
    let mut form = Submitted::new(posted);
    let action = format!("/{{ snake_plural }}/{id}");
    let Some(p) = params(&mut form) else {
        let errors = form.errors();
        let body = views::{{ snake_plural }}::form(&ui, &action, form.values(), &errors.pairs());
        return Ok(ui.page("Edit {{ snake_singular | replace(from="_", to=" ") }}", body).into_response());
    };
    let mut item = item.into_active_model();
    set(&mut item, p);
    item.update(&ctx.db).await?;
    Ok(ui.redirect(&action).ok("Saved.").into_response())
}

#[debug_handler]
async fn remove(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Redirect> {
    load(&ctx, id).await?.into_active_model().delete(&ctx.db).await?;
    Ok(ui.redirect("/{{ snake_plural }}").ok("Deleted."))
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("/{{ snake_plural }}")
        .add("/", get(list).post(create))
        .add("/new", get(new))
        .add("/{id}", get(show).post(update))
        .add("/{id}/edit", get(edit))
        .add("/{id}/delete", post(remove))
}
