//! Note pages: list, show, new, edit and delete as plain HTML forms with
//! Post/Redirect/Get. Generated by the loco-ui scaffold templates; edit freely.
#![allow(clippy::unused_async)]
use loco_rs::prelude::*;
use loco_ui::{loco::Valid, prelude::*};
#[allow(unused_imports)] // Loco lists the timestamp types too
use sea_orm::prelude::{Date, DateTimeWithTimeZone};
use serde::Deserialize;

use crate::{
    models::_entities::notes::{ActiveModel, Column, Entity, Model},
    views,
};

/// The posted fields. `Valid<Params>` reads them, or gives back a message for every field in
/// error and what was posted; add `#[validate(..)]` rules here.
#[derive(Deserialize, Validate)]
struct Params {
    title: String,
    body: Option<String>,
    #[serde(default, deserialize_with = "loco_ui::loco::checkbox")]
    done: bool,
    due: Option<Date>,
}

fn set(item: &mut ActiveModel, p: Params) {
    item.title = Set(p.title);
    item.body = Set(p.body);
    item.done = Set(p.done);
    item.due = Set(p.due);
}

async fn load(ctx: &AppContext, id: i64) -> Result<Model> {
    Entity::find_by_id(id)
        .one(&ctx.db)
        .await?
        .ok_or(Error::NotFound)
}

#[debug_handler]
async fn list(_auth: auth::JWT, ui: Ui, State(ctx): State<AppContext>) -> Result<Page> {
    let table = ui.table("notes", "");
    let wanted = query::PaginationQuery {
        page: table.page() as u64,
        page_size: table.per_page() as u64,
    };
    let found =
        query::fetch_page(&ctx.db, Entity::find().order_by_asc(Column::Id), &wanted).await?;
    Ok(ui.page("Notes", views::notes::list(&ui, &found.page, &found.meta)))
}

#[debug_handler]
async fn show(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let item = load(&ctx, id).await?;
    Ok(ui.page("Note", views::notes::show(&ui, &item)))
}

// No `State` here, so name it for the `auth::JWT` check.
#[debug_handler(state = AppContext)]
async fn new(_auth: auth::JWT, ui: Ui) -> Result<Page> {
    let title = "New note";
    let form = views::notes::form(&ui, title, "/notes", &[], &[]);
    Ok(ui.page(title, form))
}

#[debug_handler]
async fn create(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let p = match form {
        Ok(p) => p,
        Err(bad) => {
            let title = "New note";
            let body = views::notes::form(&ui, title, "/notes", &bad.values, &bad.errors.pairs());
            return Ok(ui.page(title, body).into_response());
        }
    };
    let mut item = ActiveModel {
        ..Default::default()
    };
    set(&mut item, p);
    let item = item.insert(&ctx.db).await?;
    let to = format!("/notes/{}", item.id);
    Ok(ui.redirect(&to).ok("Created.").into_response())
}

#[debug_handler]
async fn edit(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let item = load(&ctx, id).await?;
    let action = format!("/notes/{id}");
    let title = "Edit note";
    let form = views::notes::form(&ui, title, &action, &views::notes::values(&item), &[]);
    Ok(ui.page(title, form))
}

#[debug_handler]
async fn update(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let item = load(&ctx, id).await?;
    let action = format!("/notes/{id}");
    let p = match form {
        Ok(p) => p,
        Err(bad) => {
            let title = "Edit note";
            let body = views::notes::form(&ui, title, &action, &bad.values, &bad.errors.pairs());
            return Ok(ui.page(title, body).into_response());
        }
    };
    let mut item = item.into_active_model();
    set(&mut item, p);
    item.update(&ctx.db).await?;
    Ok(ui.redirect(&action).ok("Saved.").into_response())
}

#[debug_handler]
async fn remove(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Redirect> {
    load(&ctx, id)
        .await?
        .into_active_model()
        .delete(&ctx.db)
        .await?;
    Ok(ui.redirect("/notes").ok("Deleted."))
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("/notes")
        .add("/", get(list).post(create))
        .add("/new", get(new))
        .add("/{id}", get(show).post(update))
        .add("/{id}/edit", get(edit))
        .add("/{id}/delete", post(remove))
}
