//! Task pages: list, show, new, edit and delete as plain HTML forms with
//! Post/Redirect/Get. Generated by the loco-ui scaffold templates; edit freely.
#![allow(clippy::unused_async)]
use loco_rs::prelude::*;
use loco_ui::{loco::Valid, prelude::*};
#[allow(unused_imports)] // Loco lists the timestamp types too
use sea_orm::prelude::{Date, DateTime, DateTimeWithTimeZone, Decimal};
use serde::Deserialize;

use crate::{
    models::_entities::tasks::{ActiveModel, Column, Entity, Model},
    views,
};

/// The posted fields. `Valid<Params>` reads them, or gives back a message for every field in
/// error and what was posted; add `#[validate(..)]` rules here.
#[derive(Deserialize, Validate)]
struct Params {
    title: String,
    user_id: i64,
    #[serde(default, deserialize_with = "loco_ui::loco::checkbox")]
    done: bool,
    due_on: Option<Date>,
    #[serde(default, deserialize_with = "loco_ui::loco::local")]
    starts_at: Option<DateTime>,
    #[serde(default, deserialize_with = "loco_ui::loco::local")]
    remind_at: Option<DateTimeWithTimeZone>,
    price: Option<Decimal>,
    status: String,
    size: Option<i64>,
}

fn set(item: &mut ActiveModel, p: Params) {
    item.title = Set(p.title);
    item.user_id = Set(p.user_id);
    item.done = Set(p.done);
    item.due_on = Set(p.due_on);
    item.starts_at = Set(p.starts_at);
    item.remind_at = Set(p.remind_at);
    item.price = Set(p.price);
    item.status = Set(p.status);
    item.size = Set(p.size);
}

/// What each reference field can point at: every row of the parent table as `(id, label)`,
/// labelled by its name, title or email (`loco_ui::loco::label`). The form lists them in a
/// select; past a few hundred rows, swap it for `ui.combobox(..)` with a search route.
#[allow(unused_variables)] // `ctx` when the model has no references
async fn refs(ctx: &AppContext) -> Result<views::tasks::Refs> {
    Ok(views::tasks::Refs {
        user_id: crate::models::_entities::users::Entity::find()
            .all(&ctx.db)
            .await?
            .iter()
            .map(|m| (m.id.to_string(), loco_ui::loco::label(m)))
            .collect(),
    })
}

async fn load(ctx: &AppContext, id: i64) -> Result<Model> {
    Entity::find_by_id(id)
        .one(&ctx.db)
        .await?
        .ok_or(Error::NotFound)
}

#[debug_handler]
async fn list(_auth: auth::JWT, ui: Ui, State(ctx): State<AppContext>) -> Result<Page> {
    let table = ui.table("tasks", "");
    let wanted = query::PaginationQuery {
        page: table.page() as u64,
        page_size: table.per_page() as u64,
    };
    let found =
        query::fetch_page(&ctx.db, Entity::find().order_by_asc(Column::Id), &wanted).await?;
    Ok(ui.page("Tasks", views::tasks::list(&ui, &found.page, &found.meta)))
}

#[debug_handler]
async fn show(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let item = load(&ctx, id).await?;
    Ok(ui.page("Task", views::tasks::show(&ui, &item)))
}

#[debug_handler]
async fn new(_auth: auth::JWT, ui: Ui, State(ctx): State<AppContext>) -> Result<Page> {
    let title = "New task";
    let form = views::tasks::form(&ui, title, "/tasks", &[], &[], &refs(&ctx).await?);
    Ok(ui.page(title, form))
}

#[debug_handler]
async fn create(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let p = match form {
        Ok(p) => p,
        Err(bad) => {
            let title = "New task";
            let body = views::tasks::form(
                &ui,
                title,
                "/tasks",
                &bad.values,
                &bad.errors.pairs(),
                &refs(&ctx).await?,
            );
            return Ok(ui.page(title, body).into_response());
        }
    };
    let mut item = ActiveModel {
        ..Default::default()
    };
    set(&mut item, p);
    let item = item.insert(&ctx.db).await?;
    let to = format!("/tasks/{}", item.id);
    Ok(ui.redirect(&to).ok("Created.").into_response())
}

#[debug_handler]
async fn edit(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let item = load(&ctx, id).await?;
    let action = format!("/tasks/{id}");
    let title = "Edit task";
    let form = views::tasks::form(
        &ui,
        title,
        &action,
        &views::tasks::values(&item),
        &[],
        &refs(&ctx).await?,
    );
    Ok(ui.page(title, form))
}

#[debug_handler]
async fn update(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let item = load(&ctx, id).await?;
    let action = format!("/tasks/{id}");
    let p = match form {
        Ok(p) => p,
        Err(bad) => {
            let title = "Edit task";
            let body = views::tasks::form(
                &ui,
                title,
                &action,
                &bad.values,
                &bad.errors.pairs(),
                &refs(&ctx).await?,
            );
            return Ok(ui.page(title, body).into_response());
        }
    };
    let mut item = item.into_active_model();
    set(&mut item, p);
    item.update(&ctx.db).await?;
    Ok(ui.redirect(&action).ok("Saved.").into_response())
}

#[debug_handler]
async fn remove(
    _auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Redirect> {
    load(&ctx, id)
        .await?
        .into_active_model()
        .delete(&ctx.db)
        .await?;
    Ok(ui.redirect("/tasks").ok("Deleted."))
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("/tasks")
        .add("/", get(list).post(create))
        .add("/new", get(new))
        .add("/{id}", get(show).post(update))
        .add("/{id}/edit", get(edit))
        .add("/{id}/delete", post(remove))
}
